# Generated by Django 4.2.26 on 2025-11-18 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabaña',
            fields=[
                ('idCabaña', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('mantenimiento', 'En Mantenimiento'), ('reservada', 'Reservada')], default='disponible', max_length=20)),
                ('precioNoche', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Cabaña',
                'verbose_name_plural': 'Cabañas',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('tipoCliente', models.CharField(default='Regular', max_length=50)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Implemento',
            fields=[
                ('idImplemento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidadTotal', models.IntegerField()),
                ('cantidadDisponible', models.IntegerField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20)),
            ],
            options={
                'verbose_name': 'Implemento',
                'verbose_name_plural': 'Implementos',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idReserva', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('numPersonas', models.IntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('montoCotizado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comentarios', models.TextField(blank=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('cabaña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='gestion.cabaña')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='gestion.cliente')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fechaCreacion'],
            },
        ),
        migrations.CreateModel(
            name='PrestamoImplemento',
            fields=[
                ('idPrestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPrestamo', models.DateField()),
                ('fechaDevolucion', models.DateField(blank=True, null=True)),
                ('cantidad', models.IntegerField()),
                ('devuelto', models.BooleanField(default=False)),
                ('implemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='gestion.implemento')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_implementos', to='gestion.reserva')),
            ],
            options={
                'verbose_name': 'Préstamo de Implemento',
                'verbose_name_plural': 'Préstamos de Implementos',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idPago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], max_length=20)),
                ('fechaPago', models.DateField()),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gestion.reserva')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('idNotificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('alerta', 'Alerta'), ('confirmacion', 'Confirmación'), ('preparacion', 'Preparación'), ('recordatorio', 'Recordatorio'), ('general', 'General')], max_length=20)),
                ('mensaje', models.TextField()),
                ('fechaEnvio', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fechaEnvio'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('idMantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('limpieza', 'Limpieza'), ('reparacion', 'Reparación')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fechaProgramada', models.DateField()),
                ('fechaEjecucion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('cabaña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='gestion.cabaña')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['fechaProgramada'],
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('idEncuesta', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentarios', models.TextField(blank=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta', to='gestion.reserva')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
            },
        ),
    ]
