# Generated by Django 4.2.26 on 2025-11-19 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistInventario',
            fields=[
                ('idChecklist', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=100, verbose_name='Item')),
                ('cantidad_esperada', models.IntegerField(default=1, verbose_name='Cantidad Esperada')),
                ('es_obligatorio', models.BooleanField(default=True, verbose_name='Es Obligatorio')),
                ('precio_reposicion', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Reposición')),
                ('cabaña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_inventario', to='gestion.cabaña')),
            ],
            options={
                'verbose_name': 'Item de Checklist',
                'verbose_name_plural': 'Checklist de Inventario',
                'ordering': ['cabaña', 'item'],
            },
        ),
        migrations.CreateModel(
            name='EntregaCabaña',
            fields=[
                ('idEntrega', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Entrega')),
                ('cliente_confirma', models.BooleanField(default=False, verbose_name='Cliente Confirma')),
                ('observaciones_entrega', models.TextField(blank=True, verbose_name='Observaciones Entrega')),
                ('firma_digital', models.CharField(blank=True, max_length=255, verbose_name='Firma Digital')),
                ('fecha_checkout', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Check-out')),
                ('observaciones_checkout', models.TextField(blank=True, verbose_name='Observaciones Check-out')),
            ],
            options={
                'verbose_name': 'Entrega de Cabaña',
                'verbose_name_plural': 'Entregas de Cabañas',
                'ordering': ['-fecha_entrega'],
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='confirmacion_cliente',
            field=models.BooleanField(default=False, verbose_name='Confirmación Cliente'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Confirmación'),
        ),
        migrations.CreateModel(
            name='ItemFaltante',
            fields=[
                ('idItemFaltante', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_faltante', models.IntegerField(default=1, verbose_name='Cantidad Faltante')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_faltantes', to='gestion.entregacabaña')),
                ('item_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltantes', to='gestion.checklistinventario')),
            ],
            options={
                'verbose_name': 'Item Faltante',
                'verbose_name_plural': 'Items Faltantes',
                'ordering': ['entrega', 'item_checklist'],
            },
        ),
        migrations.AddField(
            model_name='entregacabaña',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='gestion.reserva'),
        ),
    ]
