# Generated by Django 4.2.26 on 2025-11-19 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0002_checklistinventario_entregacabaña_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistinventario',
            options={'ordering': ['cabaña', 'orden', 'categoria', 'nombre_item'], 'verbose_name': 'Item de Checklist', 'verbose_name_plural': 'Checklist de Inventario'},
        ),
        migrations.RemoveField(
            model_name='checklistinventario',
            name='item',
        ),
        migrations.RemoveField(
            model_name='entregacabaña',
            name='cliente_confirma',
        ),
        migrations.RemoveField(
            model_name='entregacabaña',
            name='fecha_checkout',
        ),
        migrations.RemoveField(
            model_name='entregacabaña',
            name='firma_digital',
        ),
        migrations.RemoveField(
            model_name='entregacabaña',
            name='observaciones_checkout',
        ),
        migrations.AddField(
            model_name='checklistinventario',
            name='categoria',
            field=models.CharField(choices=[('cocina', 'Cocina'), ('baño', 'Baño'), ('dormitorio', 'Dormitorio'), ('sala', 'Sala'), ('exterior', 'Exterior'), ('otros', 'Otros')], default='otros', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='checklistinventario',
            name='nombre_item',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del Item'),
        ),
        migrations.AddField(
            model_name='checklistinventario',
            name='orden',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='entregacabaña',
            name='cliente_confirma_devolucion',
            field=models.BooleanField(default=False, verbose_name='Cliente Confirma Devolución'),
        ),
        migrations.AddField(
            model_name='entregacabaña',
            name='cliente_confirma_entrega',
            field=models.BooleanField(default=False, verbose_name='Cliente Confirma Entrega'),
        ),
        migrations.AddField(
            model_name='entregacabaña',
            name='encargado_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Encargado Entrega'),
        ),
        migrations.AddField(
            model_name='entregacabaña',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Entrega'), ('entregada', 'Cabaña Entregada'), ('devuelta', 'Cabaña Devuelta'), ('verificada', 'Inventario Verificado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='entregacabaña',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Devolución'),
        ),
        migrations.AddField(
            model_name='entregacabaña',
            name='firma_digital_devolucion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Firma Digital Devolución'),
        ),
        migrations.AddField(
            model_name='entregacabaña',
            name='firma_digital_entrega',
            field=models.CharField(blank=True, max_length=255, verbose_name='Firma Digital Entrega'),
        ),
        migrations.AddField(
            model_name='entregacabaña',
            name='observaciones_devolucion',
            field=models.TextField(blank=True, verbose_name='Observaciones Devolución'),
        ),
        migrations.AlterField(
            model_name='entregacabaña',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Entrega'),
        ),
        migrations.CreateModel(
            name='ItemVerificacion',
            fields=[
                ('idItemVerificacion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_entregada', models.IntegerField(default=0, verbose_name='Cantidad Entregada')),
                ('cantidad_devuelta', models.IntegerField(default=0, verbose_name='Cantidad Devuelta')),
                ('estado_entregado', models.CharField(choices=[('bueno', 'Buen Estado'), ('regular', 'Estado Regular'), ('danado', 'Dañado'), ('faltante', 'Faltante')], default='bueno', max_length=20, verbose_name='Estado Entregado')),
                ('estado_devuelto', models.CharField(choices=[('bueno', 'Buen Estado'), ('regular', 'Estado Regular'), ('danado', 'Dañado'), ('faltante', 'Faltante')], default='bueno', max_length=20, verbose_name='Estado Devuelto')),
                ('requiere_reposicion', models.BooleanField(default=False, verbose_name='Requiere Reposición')),
                ('cargo_aplicado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cargo Aplicado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_verificacion', to='gestion.entregacabaña')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificaciones', to='gestion.checklistinventario')),
            ],
            options={
                'verbose_name': 'Item de Verificación',
                'verbose_name_plural': 'Items de Verificación',
                'ordering': ['entrega', 'item__orden', 'item__categoria'],
            },
        ),
    ]
