# Generated by Django 4.2.26 on 2025-11-20 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0003_alter_checklistinventario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaPreparacion',
            fields=[
                ('idTareaPreparacion', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('limpieza', 'Limpieza'), ('inventario', 'Inventario y Suministros'), ('mantenimiento', 'Mantenimiento Preventivo'), ('exteriores', 'Áreas Exteriores'), ('seguridad', 'Seguridad')], max_length=20, verbose_name='Categoría')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Tarea')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('es_obligatoria', models.BooleanField(default=True, verbose_name='Es Obligatoria')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Tarea de Preparación',
                'verbose_name_plural': 'Tareas de Preparación',
                'ordering': ['categoria', 'orden', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='checklistinventario',
            name='nombre_item',
            field=models.CharField(max_length=100, verbose_name='Nombre del Item'),
        ),
        migrations.CreateModel(
            name='PreparacionCabaña',
            fields=[
                ('idPreparacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Inicio')),
                ('fecha_completacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Completación')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('problemas', 'Con Problemas')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparaciones_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Encargado')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preparacion', to='gestion.reserva')),
            ],
            options={
                'verbose_name': 'Preparación de Cabaña',
                'verbose_name_plural': 'Preparaciones de Cabañas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ItemPreparacionCompletado',
            fields=[
                ('idItemPreparacion', models.AutoField(primary_key=True, serialize=False)),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Completado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('preparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_preparacion', to='gestion.preparacioncabaña')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completados', to='gestion.tareapreparacion')),
            ],
            options={
                'verbose_name': 'Item de Preparación',
                'verbose_name_plural': 'Items de Preparación',
                'ordering': ['tarea__categoria', 'tarea__orden'],
                'unique_together': {('preparacion', 'tarea')},
            },
        ),
    ]
