# Generated by Django 4.2.26 on 2025-11-22 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0004_tareapreparacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabaña',
            name='estado',
            field=models.CharField(choices=[('lista', 'Lista'), ('en_preparacion', 'En Preparación'), ('pendiente', 'Pendiente'), ('mantenimiento', 'En Mantenimiento'), ('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada')], default='disponible', max_length=20),
        ),
        migrations.CreateModel(
            name='ReporteFaltantes',
            fields=[
                ('idReporte', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(verbose_name='Descripción del Problema')),
                ('faltantes_criticos', models.BooleanField(default=True, help_text='Si está marcado, la cabaña no puede estar LISTA hasta que se resuelva', verbose_name='Faltantes Críticos')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('atendido', 'Atendido'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Atención')),
                ('observaciones_atencion', models.TextField(blank=True, verbose_name='Observaciones de Atención')),
                ('administrador_atendio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_faltantes_atendidos', to=settings.AUTH_USER_MODEL, verbose_name='Administrador que Atendió')),
                ('cabaña', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_faltantes', to='gestion.cabaña')),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_faltantes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Encargado')),
                ('preparacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_faltantes', to='gestion.preparacioncabaña', verbose_name='Preparación')),
            ],
            options={
                'verbose_name': 'Reporte de Faltantes',
                'verbose_name_plural': 'Reportes de Faltantes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
