# Generated by Django 4.2.26 on 2025-11-22 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_cabaña_estado_reportefaltantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificacionInventarioPreparacion',
            fields=[
                ('idVerificacion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_actual', models.IntegerField(default=0, verbose_name='Cantidad Actual')),
                ('cantidad_esperada', models.IntegerField(verbose_name='Cantidad Esperada')),
                ('estado_item', models.CharField(choices=[('completo', 'Completo'), ('faltante', 'Faltante'), ('no_funciona', 'No Funciona')], default='completo', max_length=20, verbose_name='Estado del Item')),
                ('verificado', models.BooleanField(default=False, verbose_name='Verificado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificaciones_preparacion', to='gestion.checklistinventario')),
                ('preparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificaciones_inventario', to='gestion.preparacioncabaña')),
            ],
            options={
                'verbose_name': 'Verificación de Inventario',
                'verbose_name_plural': 'Verificaciones de Inventario',
                'ordering': ['item__categoria', 'item__orden'],
                'unique_together': {('preparacion', 'item')},
            },
        ),
    ]
