# Generated by Django 4.2.26 on 2025-11-22 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_verificacioninventariopreparacion'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cabaña',
            table='cabana',
        ),
        migrations.AlterModelTable(
            name='checklistinventario',
            table='checklist_inventario',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
        migrations.AlterModelTable(
            name='encuesta',
            table='encuesta',
        ),
        migrations.AlterModelTable(
            name='entregacabaña',
            table='entrega_cabana',
        ),
        migrations.AlterModelTable(
            name='implemento',
            table='implemento',
        ),
        migrations.AlterModelTable(
            name='itempreparacioncompletado',
            table='item_preparacion_completado',
        ),
        migrations.AlterModelTable(
            name='itemverificacion',
            table='item_verificacion',
        ),
        migrations.AlterModelTable(
            name='mantenimiento',
            table='mantenimiento',
        ),
        migrations.AlterModelTable(
            name='notificacion',
            table='notificacion',
        ),
        migrations.AlterModelTable(
            name='pago',
            table='pago',
        ),
        migrations.AlterModelTable(
            name='preparacioncabaña',
            table='preparacion_cabana',
        ),
        migrations.AlterModelTable(
            name='prestamoimplemento',
            table='prestamo_implemento',
        ),
        migrations.AlterModelTable(
            name='reportefaltantes',
            table='reporte_faltantes',
        ),
        migrations.AlterModelTable(
            name='reserva',
            table='reserva',
        ),
        migrations.AlterModelTable(
            name='tareapreparacion',
            table='tarea_preparacion',
        ),
        migrations.AlterModelTable(
            name='verificacioninventariopreparacion',
            table='verificacion_inventario_preparacion',
        ),
        migrations.DeleteModel(
            name='ItemFaltante',
        ),
    ]
