# Generated by Django 4.2.26 on 2025-11-23 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_rename_tables_and_remove_itemfaltante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificacionInventarioPreparacion',
        ),
    ]
